### ISSUE TITLE
Bumping requests to 2.7.0 for compatibility with python 3.

### ISSUE THREAD

**Issue by meric** [waveaccounting/vero-python#5]
Is it possible to upgrade the version of requests referred to by vero-python?

I'm getting this when running with python 3 but it goes away when requests is upgraded.

```
>>> response = logger.add_user(user_id, user_data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Eric/Projects/t/gradcon5/gradcon-env/lib/python3.4/site-packages/vero/client.py", line 38, in add_user
    return self._fire_request(VeroEndpoints.ADD_USER, payload)
  File "/Users/Eric/Projects/t/gradcon5/gradcon-env/lib/python3.4/site-packages/vero/client.py", line 24, in _fire_request
    return requests.request(endpoint.method, endpoint.url, data=json_payload)
  File "/Users/Eric/Projects/t/gradcon5/gradcon-env/lib/python3.4/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/Eric/Projects/t/gradcon5/gradcon-env/lib/python3.4/site-packages/requests/sessions.py", line 335, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/Eric/Projects/t/gradcon5/gradcon-env/lib/python3.4/site-packages/requests/sessions.py", line 438, in send
    r = adapter.send(request, **kwargs)
  File "/Users/Eric/Projects/t/gradcon5/gradcon-env/lib/python3.4/site-packages/requests/adapters.py", line 292, in send
    timeout=timeout
  File "/Users/Eric/Projects/t/gradcon5/gradcon-env/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 423, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/Users/Eric/Projects/t/gradcon5/gradcon-env/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 238, in _get_conn
    return conn or self._new_conn()
  File "/Users/Eric/Projects/t/gradcon5/gradcon-env/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 562, in _new_conn
    strict=self.strict)
TypeError: __init__() got an unexpected keyword argument 'strict'
```

**Comment by ryanwilsonperkin** [comment]
That's a good idea @meric

**Comment by ryanwilsonperkin** [comment]
@meric you can now pull the update from PyPi registered as version 1.1.4
https://pypi.python.org/pypi/vero/1.1.4
